language: node_js # Node runs `npm install` and `npm test` automatically
node_js: node # Uses the latest version (via nvm)
sudo: true # Allows Travis to run this project in container
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
